name: ventouras
favicon: null
layout_spectrum: 0.988
typography_spectrum: 0.76628
title: Nikolaos Ventouras
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#69331b'
    - '#d7bfa3'
    - '#ae9577'
    - '#130a0b'
    - '#ffffeb'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
